blank_issues_enabled: false
contact_links:
  - name: üéôÔ∏è Discussions
    url:  https://github.com/BlackArch/blackarch/discussions
    about: Start a discussion here.
  - name: Matrix
    url:  https://matrix.to/#/#BlackArch:matrix.org
    about: Come keep us company. We have a little community here. Anything is on topic but the large majority of discussion is related to security and/or BlackArch.
  - name: Website
    url: https://blackarch.org/index.html
    about: Our official website.
  - name: X
    url: https://x.com/blackarchlinux
    about: Follow us on X! We mainly tweet about new tools, new mirrors, and major project changes.
  - name: Youtube
    url: https://www.youtube.com/channel/UChw5hByy70ey2F7QeLEGICQ
    about: Follow us and subscribe on our YouTube channel! We mainly upload self-made videos about installation, configuration, and major tool usage.
